language: php

stages:
  - pre-conditions
  - test
  - quality

php:
  - 7.2
  - 7.3

env:
  - COMMAND="composer install"
  - COMMAND="composer update"

before_script:
  - ${COMMAND}

script:
  - vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-php.sh
  - php vendor/phpunit/phpunit/phpunit --no-coverage

jobs:
  fast_finish: true

  allow_failures:
    - php: 7.3
      env: Psalm
    - php: 7.3
      env: PHP Codesniffer

  include:
    - stage: pre-conditions
      env: Syntax checks
      before_script:
        - composer require simplesamlphp/simplesamlphp-test-framework --dev
      script:
        - vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-xml.sh
        - vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-yaml.sh

    - stage: pre-conditions
      env: Security check
      before_script:
        - composer require sensiolabs/security-checker --dev
      script:
        - vendor/bin/security-checker security:check


    - stage: quality
      php: 7.2
      env: Codecov
      before_script:
        - composer require phpunit/phpunit --dev
        - php vendor/phpunit/phpunit/phpunit
      script:
        # Codecov, need to edit bash uploader for incorrect TRAVIS_PYTHON_VERSION environment variable matching, at least until codecov/codecov-bash#133 is resolved
        - curl -s https://codecov.io/bash > .codecov
        - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
        - chmod +x .codecov
        - ./.codecov -X gcov
        # - <(curl -s https://codecov.io/bash)

    - stage: quality
      php: 7.3
      env: Psalm
      before_script:
        - composer require vimeo/psalm --dev
      script:
        - vendor/bin/psalm

    - stage: quality
      php: 7.3
      env: PHP Codesniffer
      before_script:
        - composer require squizlabs/php_codesniffer --dev
      script:
        - vendor/bin/phpcs src/
